### ISSUE TITLE
computed的watcher那里有个问题

### ISSUE THREAD

**Issue by blueprint1453** [naihe138/write-vue#2]
有个问题请教，computed的watcher那个流程，为什么我觉得watcher.dirty是false啊，因为数据更新后普通的watcher（渲染watcher）在前面，computed的watcher的update是在后面，那么watcher.dirty应该还是false，里面的evaluate也就不会运行

这里问题指的是公众号文章，computed属性依赖的数据更新后的情况 https://mp.weixin.qq.com/s/kBO6iZ8s120QscaKSIO5Zg

**Comment by naihe138** [comment]
代码都实现王完成之后，我们说下流程，

* 1、首先在`render`函数里面会读取`this.info`，这个会触发`createComputedGetter(key)`中的`computedGetter(key)`；
* 2、然后会判断`watcher.dirty`，执行`watcher.evaluate()`；
* 3、进到`watcher.evaluate()`，才真想执行`this.get`方法，这时候会执行`pushTarget(this)`把当前的`computed watcher` push到stack里面去，并且把`Dep.target 设置成当前的`computed watcher`；
* 4、然后运行`this.getter.call(vm, vm)` 相当于运行`computed`的`info: function() { return this.name + this.age }`，这个方法；
* 5、`info`函数里面会读取到`this.name`，这时候就会触发数据响应式`Object.defineProperty.get`的方法，这里`name`会进行依赖收集，把`watcer`收集到对应的`dep`上面；并且返回`name = '张三'`的值，`age`收集同理；
* 6、依赖收集完毕之后执行`popTarget()`，把当前的`computed watcher`从栈清除，返回计算后的值('张三+10')，并且`this.dirty = false`；
* 7、`watcher.evaluate()`执行完毕之后，就会判断`Dep.target` 是不是`true`，如果有就代表还有`渲染watcher`，就执行`watcher.depend()`，然后让`watcher`里面的`deps`都收集`渲染watcher`，这就是双向保存的优势。
* 8、此时`name`都收集了`computed watcher` 和 `渲染watcher`。那么设置`name`的时候都会去更新执行`watcher.update()`
* 9、如果是`computed watcher`的话不会重新执行一遍只会把`this.dirty` 设置成 `true`，如果数据变化的时候再执行`watcher.evaluate()`进行`info`更新，没有变化的的话`this.dirty` 就是`false`，不会执行`info`方法。这就是computed缓存机制。
